services:
  # PHP-ERAVIS2
  php:
    build:
      context: ./docker/php
    extra_hosts:
    - "host.docker.internal:host-gateway"
    container_name: php
    volumes:
      - ./.:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - transdoliu-network
      - mysql

  # Nginx-ERAVIS2
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./.:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - transdoliu-network
    depends_on:
      - php

networks:
  transdoliu-network:
    name: transdoliu-network
    driver: bridge
  mysql:
    external: true
